server:
  # port: 80
  port: 8082
  servlet:
    context-path: /display   # 访问时要加这个前缀
#  ssl:
#    enabled: true
#    key-store: /key_store.jks
#    key-store-password: key_store_pwd

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bgp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 123456789
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: true
    mode: HTML
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.bgpm.pojo